### ISSUE TITLE
database.pg_dump: POSIX tar archive

### ISSUE THREAD

**Issue by roughnecks** [lelutin/backupninja#3]
Hello,

I just extracted a `.tar.bz2` which has my postgresql databases backup..
I get a directory with `database_names.pg_dump.gz` files, so I gunzipped the one I needed and ran:

`file database.pg_dump`

and it tells me `database.pg_dump: POSIX tar archive`

Is this OK? I searched and read this on "stackoverflow":
> So depends on the way it was dumped out. If using Linux/Unix, you can probably figure it out using the excellent file(1) command - if it mentions ASCII text and/or SQL, it should be restored with [psql](https://www.postgresql.org/docs/current/app-psql.html) otherwise you should probably use [pg_restore](https://www.postgresql.org/docs/current/app-pgrestore.html).

Can you shed some light? Thanks

**Comment by lelutin** [comment]
Hi there!

Was your archive created by backupninja? If so, I believe it is producing "plain"-type gzipped archives which would normally not have `.tar` in the name since a tar archive is not being created by the handler.

If this might interest you, the lines that produce the pgsql dumps is here when asking for a dump of all DBs:

https://0xacab.org/liberate/backupninja/-/blob/master/handlers/pgsql.in?ref_type=heads#L67

and here when individual DBs are requested:

https://0xacab.org/liberate/backupninja/-/blob/master/handlers/pgsql.in?ref_type=heads#L125


if your archive was not produced by backupninja, then as ppl said on stackoverflow, it depends on how the archive was produced.
check out the documentation for pg_dump which is usually used to produce pgsql dump files, especially the `--format` option specifies that one of the formats is a "tar archive", so it's possible that pg_restore will accept your file `database.pg_dump` as-is. https://www.postgresql.org/docs/current/app-pgdump.html 
So one thing you can do just to make sure you won't lose data if something goes wrong is that you can create a new database with a dummy name, then try to restore your dump file to that new database and see if it gets accepted without changes. If it does, you can then decide whether or not you want to risk restoring the file to a more critical database (and possibly drop the test database with the dummy name).


Also, please note that if you need further assistance with the backupninja backup coordination tool, this repository is only a mirror of the upstream backupninja project, which you can find at https://0xacab.org/liberate/backupninja -- so I'm not using this repo to centralize patches / issue reports and other contributions: the best to get help with backupninja would be to refer to the upstream project at the URL just above.
